// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HouseRentMVCML.Model
{
    public class ModelInput
    {
        [ColumnName("Locality"), LoadColumn(0)]
        public string Locality { get; set; }


        [ColumnName("Area"), LoadColumn(1)]
        public float Area { get; set; }


        [ColumnName("Bedrooms"), LoadColumn(2)]
        public float Bedrooms { get; set; }


        [ColumnName("Furnishing"), LoadColumn(3)]
        public string Furnishing { get; set; }


        [ColumnName("Price"), LoadColumn(4)]
        public float Price { get; set; }


    }
}
